config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :products, only:[:index, :new, :create, :destroy]
  resources :clients, only:[:index, :new, :create, :destroy]
  resources :slips do
    member do
      get 'output'
    end
    collection do
      get 'search'
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/_top_category.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" fill="currentColor" class="bi bi-bag-plus-fill" id="navibtn" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zM8.5 8a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V12a.5.5 0 0 0 1 0v-1.5H10a.5.5 0 0 0 0-1H8.5V8z"/>
      </svg>
      <div class="card-body">
        <h5 class="card-title fw-bold fs-2"><%= link_to "商品を登録する", new_product_path %></h5>
        <p class="card-text fw-bold" id="description">商品を一括で事前登録することができます。</p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-right ms-3" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
          <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
        </svg>
        <%= link_to "登録済み商品一覧へ", products_path, class:"btn btn-primary", id:"ichiran-btn" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" fill="currentColor" class="bi bi-send-plus" id="navibtn" viewBox="0 0 16 16">
        <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855a.75.75 0 0 0-.124 1.329l4.995 3.178 1.531 2.406a.5.5 0 0 0 .844-.536L6.637 10.07l7.494-7.494-1.895 4.738a.5.5 0 1 0 .928.372l2.8-7Zm-2.54 1.183L5.93 9.363 1.591 6.602l11.833-4.733Z"/>
        <path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-3.5-2a.5.5 0 0 0-.5.5v1h-1a.5.5 0 0 0 0 1h1v1a.5.5 0 0 0 1 0v-1h1a.5.5 0 0 0 0-1h-1v-1a.5.5 0 0 0-.5-.5Z"/>
      </svg>
      <div class="card-body">
        <h5 class="card-title fw-bold fs-2"><%= link_to "取引先を登録する", new_client_path %></h5>
        <p class="card-text fw-bold" id="description">取引先を一括で事前登録することができます。</p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-right ms-3" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
          <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
        </svg>
        <%= link_to "登録済み取引先一覧へ", clients_path, class:"btn btn-primary", id:"ichiran-btn" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 mt-3">
    <div class="card">
      <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" fill="currentColor" class="bi bi-file-plus" id="navibtn" viewBox="0 0 16 16">
        <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
      </svg>
      <div class="card-body">
        <h5 class="card-title fw-bold fs-2"><%= link_to '伝票を作成する', new_slip_path %></h5>
        <p class="card-text fw-bold" id="description">●フォーマットに沿って簡単に伝票を作成することができます。</p>
        <p class="card-text fw-bold" id="description">●登録済の商品から使いたい商品を選択式で入力できます。</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 mt-3">
    <div class="card">
      <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" fill="currentColor" class="bi bi-folder" id="navibtn" viewBox="0 0 16 16">
        <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
      </svg>
      <div class="card-body">
        <h5 class="card-title fw-bold fs-2"><%= link_to '作成済み伝票を確認する', slips_path %></h5>
        <p class="card-text fw-bold" id="description">●作成済みの伝票を一覧で確認することができます。</p>
        <p class="card-text fw-bold" id="description">●登録済の取引先から使いたい出荷先を選択式で入力できます。</p>
      </div>
    </div>
  </div>
</div>
  
  

app/views/tops/_top_center.html.erb
<div class="center d-flex justify-content-center border border-light border-2 my-1">
  <img src="トップページ画像.png" class="h-100" alt="...">
</div>

app/views/tops/_top_header.html.erb
<ul class="nav nav-pills navbar-light bg-light">
  <li class="nav-item d-flex">
    <p class="app-logo-block"><img src="easy_slips_logo.png" class="app-logo" alt="..."></p>
    <h1 class="app-name">Easy Slips</h1>
  </li>
  <li class="nav-item dropdown">
    <% if user_signed_in? %>
      <a class="nav-link dropdown-toggle h3" data-bs-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
      </ul>
    <% else %>
      <a class="nav-link dropdown-toggle h3" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">新規登録orログイン</a>
      <ul class="dropdown-menu">
        <li><%= link_to 'ログイン', new_user_session_path, class:"dropdown-item" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class:"dropdown-item" %></li>
      </ul>
    <% end %>
  </li>
</ul>

app/views/tops/index.html.erb
<div class="container"> 
  <%= render "top_header" %>
  <%= render "top_center"%>
  <%= render "top_category"%>
</div> 