config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :products, only:[:index, :new, :create, :destroy]
  resources :clients, only:[:index, :new, :create, :destroy]
  resources :slips do
    member do
      get 'output'
    end
    collection do
      get 'search'
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :availability, inclusion: { in: [true, false] }
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @clients = Client.all.order('created_at DESC')
  end

  def new
    @form = Form::ClientCollection.new
  end

  def create
    @form = Form::ClientCollection.new(client_collection_params)
    if @form.save
      redirect_to clients_path
    else
      render :new
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end

  private

    def client_collection_params
        params.require(:form_client_collection)
        .permit(clients_attributes: [:name, :availability])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_lists(clients)
    html = ''
    clients.each do |client|
      html += render(partial: "client", locals: { client: client }) 
    end
    return raw(html)
  end
end

app/views/clients/_client.html.erb
<tr class="item">
  <td>
    <%= client.created_at.strftime('%Y/%m/%d') %>
  </td>
  <td>
    <%= client.name %>
  </td>
  <td>
    <%= link_to "削除", client_path(client.id), method: :delete, class: 'btn btn-danger', id: "element-delete" %>
  </td>
</tr>

app/views/clients/_error_messages.html.erb
<% if @form.clients.any? { |client| client.errors.present? } %>
  <div class="alert alert-danger">
    <% @form.clients.each do |client| %>
      <% if client.errors.present? %>
      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/clients/index.html.erb
<h2 class="text-center bg-primary text-white">登録済み取引先一覧</h2>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>登録日</th>
        <th>取引先名</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="bulk-registration-form">
      <%= client_lists(@clients) %>
    </tbody>
  </table>
  <% if @clients.length == 0 %>
    <div class="card text-center mt-3 mb-5">
      <div class="card-body">
        <h5 class="card-title text-danger">※取引先が登録されていません※</h5>
      </div>
    </div>
  <% end %>
</div>
<div class="text-center mt-3">
  <%= link_to "戻る", root_path, class: 'btn btn-success' %>
</div>  

app/views/clients/new.html.erb
<h2 class="text-center bg-primary text-white">新規取引先登録</h2>

<div class="container">
  <div class="card text-center mt-3 mb-5">
    <div class="card-body">
      <h5 class="card-title text-danger">※登録前に必ずチェックボックスにチェックを入れてください。※<br>チェックを入れた取引先のみが一括で登録されます。</h5>
    </div>
  </div>

  <%= form_with model: @form, url: clients_path, method: :post, class:"input-client mb-5", local: true do |fb| %>

  <%= render partial:'error_messages', model: @form %> 
  
    <table class="table">
      <thead>
        <tr>
          <th width="80px", class="text-center h3">
            <strong>登録</strong>
          </th>
          <th class="text-center h3">
            <strong>取引先名</strong>
          </th>
        </tr>
      </thead>
      <tbody class="registration-form">
        <%= fb.fields_for :clients do |f| %>
          <tr class="item">
            <td class="text-center">
              <%= f.check_box :availability, class: 'top10 registration-checkbox' %>
            </td>
            <td>
              <%= f.text_field :name, class: 'form-control' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= fb.submit '一括登録', class: 'btn btn-primary' %>
      <%= link_to "戻る", root_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>