config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :products, only:[:index, :new, :create, :destroy]
  resources :clients, only:[:index, :new, :create, :destroy]
  resources :slips do
    member do
      get 'output'
    end
    collection do
      get 'search'
    end
  end
end

app/models/slip.rb
class Slip < ApplicationRecord
  with_options presence: true do
    validates :address_name
    validates :shipping_date
    validates :slip_number, length: { maximum: 10 }
  end
  validates :invoice_number, length: { maximum: 10 }

  has_many :orders, dependent: :destroy 
  accepts_nested_attributes_for :orders, allow_destroy: true

  def self.search(search)
    if search != ""
      Slip.where('slip_number LIKE(?)', "%#{search}%")
    else
      Slip.all
    end
  end
end

app/controllers/slips_controller.rb
class SlipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_slip, only: [:show, :edit, :update, :destroy, :output]

  def index
    @slips = Slip.all.order('created_at DESC')
  end

  def new
    @slip = Slip.new
    10.times do
      @order = @slip.orders.new
    end
  end

  def create
    @slip = Slip.new(slip_params)
    unless @slip.save
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @slip.update(slip_params)
      redirect_to slip_path(@slip.id)
    else
      render :edit
    end
  end

  def destroy
    @slip.destroy
    redirect_to slips_path
  end

  def output
    report = Thinreports::Report.new(layout: "#{Rails.root}/app/pdfs/easy_slips.tlf")

    report.start_new_page

    report.page.item(:address_name).value(@slip.address_name)
    report.page.item(:company).value(current_user.name)
    report.page.item(:shipping_date).value(@slip.shipping_date)
    report.page.item(:slip_number).value(@slip.slip_number)
    report.page.item(:invoice_number).value(@slip.invoice_number)

    total = 0 
    @slip.orders.each do |order| 
      report.list.add_row do |row| 
        row.item(:order_number).value(order.order_number)
        row.item(:color).value(order.color)
        row.item(:count).value(order.count)
        row.item(:note).value(order.note)
      end
      if order.count.present? 
        total += order.count 
      end
    end
    report.page.item(:total).value(total) 
  
    file = report.generate

    send_data(
      file,
      filename: "easy_slips.pdf",
      type: "application/pdf",
      disposition: "inline")
  end

  def search
    # ransackで検索用のオブジェクトを生成し、params[:q]でフォームから来たデータを受ける
    @q = Slip.ransack(params[:q])
    # resultで検索結果を取得し、インスタンス変数@slipsに代入
    @slips = @q.result
  end

  private

  def slip_params
    params.require(:slip).permit(:address_name, :shipping_date, :slip_number, :invoice_number, orders_attributes: [:order_number, :color, :count, :note, :_destroy, :id])
  end

  def set_slip
    @slip = Slip.find(params[:id])
  end
end

app/helpers/slips_helper.rb
module SlipsHelper
  def slip_lists(slips)
    html = ''
    slips.each do |slip|
      html += render(partial: "slip", locals: { slip: slip }) 
    end
    return raw(html)
  end

  def slip_order_lists(orders)
    html = ''
    orders.each do |order| 
      html += render(partial: "slip_order", locals: { order: order }) 
    end
    return raw(html)
  end
end

app/views/slips/_error_messages.html.erb
<% if @slip.errors.any? %>
  <div class="error-alert">
    <ul>
      <% @slip.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/slips/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <th>【出荷先】</th>
    <%= fb.collection_select :address_name, Client.select(:name).distinct, :name, :name, {include_blank: "--"}, class: "form-control" %>
  </div>
  <div class="col-md-6">
    <th>【送り主】</th>
    <p class="h2">
    <%= current_user.name %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <th>【出荷日】</th>
    <%= fb.date_field :shipping_date, class: 'form-control' %>
  </div>
  <div class="col-md-4">
    <th>【伝票番号】</th>
    <%= fb.text_field :slip_number, class: 'form-control' %>
  </div>
  <div class="col-md-4">
    <th>【送り状ナンバー】</th>
    <%= fb.text_field :invoice_number, class: 'form-control' %>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>品番</th>
      <th>色</th>
      <th>数量</th>
      <th>備考</th>
    </tr>
  </thead>
  <tbody class="bulk-registration-form">
    <%= fb.fields_for :orders do |f| %>
      <tr class="item">
        <td>
          <%= f.collection_select :order_number, Product.select(:item_number).distinct, :item_number, :item_number, {include_blank: "--"}, class: "form-control" %>
        </td>
        <td>
          <%= f.collection_select :color, Product.select(:color).distinct, :color, :color, {include_blank: "--"}, class: "form-control" %>
        </td>
        <td>
          <%= f.text_field :count, class: 'form-control' %>
        </td>
        <td>
          <%= f.text_field :note, class: 'form-control' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/slips/_slip.html.erb
<div class="col-sm-4">
  <div class="card mt-3">
    <div class="card-body text-center">
      <h5 class="card-title">伝票番号：<%= slip.slip_number %></h5>
      <p class="card-text">出荷先：<%= slip.address_name %></p>
      <p class="card-text">出荷日：<%= slip.shipping_date %></p>
      <p class="card-text">作成日：<%= slip.created_at.strftime('%Y/%m/%d') %></p>
      <%= link_to "詳細", slip_path(slip.id), class:"card-link"%>
      <%= link_to "削除", slip_path(slip.id), method: :delete, class:"card-link"%>
    </div>
  </div>
</div>

app/views/slips/_slip_order.html.erb
<% if order.order_number.present? %>
  <tr class="item">
    <td>
      <%= order.order_number %>
    </td>
    <td>
      <%= order.color %>
    </td>
    <td>
      <%= order.count %>
    </td>
    <td>
      <%= order.note %>
    </td>
  </tr> 
<% end %>

app/views/slips/create.html.erb
<div class="container">
  <div class="text-center">
    <h1>伝票の作成が完了しました。</h1>
    <%= link_to "トップへ戻る", root_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/slips/edit.html.erb
<div class="d-grid gap-5">
<h2 class="text-center bg-primary text-white">伝票編集</h2>

<%= render partial:'error_messages', model: @slip %> 

<div class="container">
  <%= form_with model: @slip, url: slip_path, method: :patch, class:"mb-5", local: true do |fb| %>
    
    <%= render partial:'form', locals: { fb: fb } %> 
    
    <div class="text-center">
      <%= fb.submit '更新', class: 'btn btn-primary' %>
      <%= link_to "戻る", root_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/slips/index.html.erb
<h2 class="text-center bg-primary text-white">作成済み伝票一覧</h2>
<div class="container">
  <h3 class="text-center mt-3">
    <%= link_to '作成済み伝票検索へ', search_slips_path %>
  </h3>
  <div class="row">
    <%= slip_lists(@slips) %>
  </div>
  <% if @slips.length == 0 %>
    <div class="card text-center mt-3 mb-5">
      <div class="card-body">
        <h5 class="card-title text-danger">※伝票を作成してください※</h5>
      </div>
    </div>
  <% end %>
  <div class="text-center mt-3">
    <%= link_to "戻る", root_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/slips/new.html.erb
<div class="d-grid gap-5">
<h2 class="text-center bg-primary text-white">新規伝票作成</h2>

<%= render partial:'error_messages', model: @slip %> 

<div class="container">
  <%= form_with model: @slip, url: slips_path, method: :post, class:"mb-5", local: true do |fb| %>
    
    <%= render partial:'form', locals: { fb: fb } %> 

    <div class="text-center">
      <%= fb.submit '登録', class: 'btn btn-primary' %>
      <%= link_to "戻る", root_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/slips/search.html.erb
<h2 class="text-center bg-primary text-white">伝票検索</h2>
<div class="container">
  <h3 class="title mt-3">＜＜検索項目＞＞</h3>
  <div class="mt-1">
    <%= search_form_for @q, url: search_slips_path, html: {id: "detailed-search-form"} do |f| %>
      <div class="d-flex">
        <div class="search-field">
          <%= f.label :slip_number_cont, '【伝票番号】' , class: "search-category"%>
          <br>
          <%= f.text_field :slip_number_cont, placeholder: '伝票番号', class: "search-category" %>
        </div>
        <div class="search-field ms-3">
          <%= f.label :address_name_cont, '【出荷先】', class: "search-category" %>
          <br>
          <%= f.text_field :address_name_cont, placeholder: '出荷先', class: "search-category" %>
        </div>
      </div>
      <div class="d-flex mt-2">
        <div class="search-field">
          <%= f.label :shipping_date_gteq, '【出荷日】', class: "search-category" %>
          <br>
          <%= f.date_field :shipping_date_gteq, placeholder: '出荷日', class: "search-category" %>
          ~
          <%= f.date_field :shipping_date_lteq, placeholder: '出荷日', class: "search-category" %>
        </div>
        <div class="search-field ms-3">
          <%= f.label :created_at_gteq, '【作成日】', class: "search-category" %>
          <br>
          <%= f.date_field :created_at_gteq, placeholder: '作成日', class: "search-category" %>
          ~
          <%= f.date_field :created_at_lteq, placeholder: '作成日', class: "search-category" %>
        </div>
      </div>
      <%= f.submit '検索', class: 'btn btn-primary mt-3' %>
    <% end %>
  </div>
  <div class="row">
    <%= slip_lists(@slips) %>
  </div>
  <div class="text-center mt-3">
    <%= link_to "戻る", slips_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/slips/show.html.erb
<div class="d-grid gap-5">
  <h2 class="text-center bg-primary text-white">伝票詳細</h2>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <th>【出荷先】</th>
        <div class="form-control">
          <%= @slip.address_name %>
        </div>
      </div>
      <div class="col-md-6">
        <th>【送り主】</th>
        <p class="h2">
          <%= current_user.name %>
        </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <th>【出荷日】</th>
        <div class="form-control">
          <%= @slip.shipping_date %>
        </div>
      </div>
      <div class="col-md-4">
        <th>【伝票番号】</th>
        <div class="form-control">
          <%= @slip.slip_number %>
        </div>
      </div>
      <div class="col-md-4">
        <th>【送り状ナンバー】</th>
        <div class="form-control">
          <% if @slip.invoice_number.present? %>
            <%= @slip.invoice_number %>
          <% else %>
            なし
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>品番</th>
          <th>色</th>
          <th>数量</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody class="bulk-registration-form">
        <%= slip_order_lists(@slip.orders) %>
      </tbody>
    </table>
  </div>
</div>
<div class="text-center mt-3">
  <%= link_to "PDF出力", output_slip_path(@slip.id), class: 'btn btn-danger' %>
  <%= link_to "編集", edit_slip_path(@slip.id), class: 'btn btn-primary' %>
  <%= link_to "削除", slip_path(@slip.id), method: :delete, class: 'btn btn-primary' %>
</div>
<div class="text-center mt-3">
  <%= link_to "戻る", slips_path, class: 'btn btn-success' %>
</div>  