config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :products, only:[:index, :new, :create, :destroy]
  resources :clients, only:[:index, :new, :create, :destroy]
  resources :slips do
    member do
      get 'output'
    end
    collection do
      get 'search'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  with_options presence: true do
    validates :item_number, length: { maximum: 10 }
    validates :color
    validates :note, length: { maximum: 20 }
    validates :availability, inclusion: { in: [true, false] }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @products = Product.all.order('created_at DESC')
  end

  def new
    @form = Form::ProductCollection.new
  end

  def create
    @form = Form::ProductCollection.new(product_collection_params)
    if @form.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

    def product_collection_params
        params.require(:form_product_collection)
        .permit(products_attributes: [:item_number, :color, :note, :availability])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  def product_lists(products)
    html = ''
    products.each do |product|
      html += render(partial: "product", locals: { product: product }) 
    end
    return raw(html)
  end
end

app/views/products/_error_messages.html.erb
<% if @form.products.any? { |product| product.errors.present? } %>
  <div class="alert alert-danger">
    <% @form.products.each do |product| %>
      <% if product.errors.present? %>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr class="item">
  <td>
    <%= product.created_at.strftime('%Y/%m/%d') %>
  </td>
  <td>
    <%= product.item_number %>
  </td>
  <td>
    <%= product.color %>
  </td>
  <td>
    <%= product.note %>
  </td>
  <td>
    <%= link_to "削除", product_path(product.id), method: :delete, class: 'btn btn-danger', id: "element-delete"%>
  </td>
</tr>

app/views/products/index.html.erb
<h2 class="text-center bg-primary text-white">登録済み商品一覧</h2>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>登録日</th>
        <th>品番</th>
        <th>色</th>
        <th>備考</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="bulk-registration-form">
      <%= product_lists(@products) %>
    </tbody>
  </table>
  <% if @products.length == 0 %>
    <div class="card text-center mt-3 mb-5">
      <div class="card-body">
        <h5 class="card-title text-danger">※商品が登録されていません※</h5>
      </div>
    </div>
  <% end %>
</div>
<div class="text-center mt-3">
  <%= link_to "戻る", root_path, class: 'btn btn-success' %>
</div>  

app/views/products/new.html.erb
<h2 class="text-center bg-primary text-white">新規商品登録</h2>

<div class="container">
  <div class="card text-center mt-3 mb-5">
    <div class="card-body">
      <h5 class="card-title text-danger">※登録前に必ずチェックボックスにチェックを入れてください。※<br>チェックを入れた商品のみが一括で登録されます。</h5>
    </div>
  </div>

  <%= form_with model: @form, url: products_path, method: :post, class:"input-product mb-5", local: true do |fb| %>

  <%= render partial:'error_messages', model: @form %>

    <table class="table">
      <thead>
        <tr>
          <th width="60px">登録</th>
          <th>品番</th>
          <th>色</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody class="bulk-registration-form">
        <%= fb.fields_for :products do |f| %>
          <tr class="item">
            <td class="text-center">
              <%= f.check_box :availability, class: 'top10 registration-checkbox' %>
            </td>
            <td>
              <%= f.text_field :item_number, class: 'form-control' %>
            </td>
            <td>
              <%= f.text_field :color, class: 'form-control' %>
            </td>
            <td>
              <%= f.text_field :note, class: 'form-control' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= fb.submit '一括登録', class: 'btn btn-primary' %>
      <%= link_to "戻る", root_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>